services:
  - type: web
    name: analise-senadores-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: MYSQL_HOST
        fromDatabase:
          name: postgres-db
          property: host
      - key: MYSQL_PORT
        fromDatabase:
          name: postgres-db
          property: port
      - key: MYSQL_DATABASE
        fromDatabase:
          name: postgres-db
          property: database
      - key: MYSQL_USER
        fromDatabase:
          name: postgres-db
          property: user
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: postgres-db
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: SERVER_PORT
        value: 10000
      - key: CORS_ALLOWED_ORIGINS
        value: "*"

databases:
  - name: postgres-db
    plan: free
    databaseName: analise_senadores
    user: app_user
